#!/usr/bin/env python3
"""Generate the GitHub Copilot adapter from the canonical skills.

Produces, in the target repo:
    .github/prompts/<skill>.prompt.md    one per skills/*/SKILL.md (explicit /name invocation)
    .github/skills/<name>/SKILL.md       one per skills/*/SKILL.md (native, model-invoked)
    .github/agents/<name>.agent.md       one per agents/*.md (Copilot custom agents)
    .github/copilot-instructions.md      framework overview + shared rules
and, in the stack repo itself:
    AGENTS.md                            universal entry point (AGENTS.md-aware tools)

Canonical content lives in skills/; regenerate after editing them. Generated
files carry a marker line and are only overwritten when the marker is present,
so hand-created files are never clobbered.

Usage:
    build_copilot.py [--target /path/to/work-repo] [--stack-root /path/to/this-repo]

Default target is the stack repo. When targeting a work repo, path references
in prompts point back at the stack root by absolute path.
"""
import argparse
import re
import sys
from pathlib import Path

MARKER = "generated by software-engineer-stack scripts/build_copilot.py; do not edit by hand"


def parse_frontmatter(text: str, path: Path) -> tuple[dict, str]:
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not m:
        sys.exit(f"error: {path}: no frontmatter block")
    fm = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            fm[k.strip()] = v.strip().strip('"').strip("'")
    if "name" not in fm or "description" not in fm:
        sys.exit(f"error: {path}: frontmatter missing name/description")
    return fm, m.group(2)


def write_generated(path: Path, content: str) -> None:
    if path.exists() and MARKER not in path.read_text():
        sys.exit(f"error: {path} exists and was not generated by this script — refusing to overwrite")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"wrote {path}")


def build_prompt(fm: dict, body: str, root_ref: str) -> str:
    body = body.replace("${CLAUDE_PLUGIN_ROOT}", root_ref)
    args = f"\n> Arguments: `{fm['argument-hint']}`" if fm.get("argument-hint") else ""
    return f"""---
description: {fm['description']}
mode: agent
---
<!-- {MARKER} -->
> Part of **software-engineer-stack** ({root_ref}). Shared decision protocol:
> {root_ref}/core/decision-protocol.md — follow it for every unknown.{args}

{body}"""


def build_skill(fm: dict, body: str, root_ref: str) -> str:
    body = body.replace("${CLAUDE_PLUGIN_ROOT}", root_ref)
    return f"""---
name: {fm['name']}
description: {fm['description']}
---
<!-- {MARKER} -->
{body}"""


def build_agent(fm: dict, body: str, root_ref: str) -> str:
    body = body.replace("${CLAUDE_PLUGIN_ROOT}", root_ref)
    return f"""---
name: {fm['name']}
description: {fm['description']}
---
<!-- {MARKER} -->
> Part of **software-engineer-stack** ({root_ref}). You are read-only: report
> findings in your defined format; never modify files or repository state.

{body}"""


def build_instructions(root_ref: str, skill_names: list[str]) -> str:
    cmds = ", ".join(f"`/{n}`" for n in skill_names)
    return f"""<!-- {MARKER} -->
# software-engineer-stack — Copilot instructions

This repository is worked on with the software-engineer-stack lifecycle
framework rooted at `{root_ref}`. The stages are available two ways with the
same instructions: explicitly as prompt files in Copilot Chat ({cmds}) and as
native agent skills in `.github/skills/` which the Copilot CLI and coding
agent load automatically when a request matches a stage's description.

Rules that apply to ALL work here:

1. **Decision protocol** (`{root_ref}/core/decision-protocol.md`): checkable
   facts are checked, never estimated. Proceed without asking only on
   ~90%+-confident, cheaply-reversible, in-scope calls with no dangerous
   surface — logged to the task workspace `ASSUMPTIONS.md`. Everything else
   (genuinely unknown, irreversible, data/prod-touching, scope-affecting)
   stops and asks. Open assumptions are ratified at every approval gate.
2. **Scope discipline**: the task's `work/<id>/scope-contract.md` is the
   single source of scope truth. Out-of-scope findings go to `PARKED.md`,
   never into the change.
3. **Conventions**: this repo's `.conventions.md` (generate with the
   repo-profile prompt if missing) overrides the framework defaults in
   `{root_ref}/standards/`; the file being edited overrides both.
4. **Verification**: code claims require evidence — run it (see the
   verify-code prompt) and capture output to the workspace `evidence/`
   directory. Fallback static checks must be labelled as such.
5. **Resumability**: the task workspace `STATUS.md` records stage state;
   read it before starting, update it after every stage transition.
6. The review procedures (scope-auditor, code-reviewer, doc-fact-checker)
   are installed as Copilot custom agents in `.github/agents/` — where a
   prompt says to run one, delegate to the matching custom agent (VS Code,
   Copilot CLI `/agents`, or the coding agent). On a surface without
   custom-agent support, execute the procedure from `{root_ref}/agents/`
   yourself as a separate, fresh review pass held to its report format.
"""


def build_agents_md(skill_dirs: list[Path]) -> str:
    rows = []
    for d in skill_dirs:
        fm, _ = parse_frontmatter((d / "SKILL.md").read_text(), d / "SKILL.md")
        desc = fm["description"].split(". ")[0].rstrip(".")
        rows.append(f"| `/{fm['name']}` | {desc}. | `skills/{d.name}/SKILL.md` |")
    table = "\n".join(rows)
    return f"""<!-- {MARKER} -->
# software-engineer-stack

An end-to-end software engineering lifecycle framework for PL/SQL, SQL, KSH,
and Python codebases: brief → research → technical design → implementation
plan → verified code → audited delivery, plus fast paths for change requests
and documentation. Full docs: README.md.

## How any agent should use this repo

1. Read `core/decision-protocol.md` first — it governs every unknown
   (check facts; proceed-and-log only narrow, reversible calls; otherwise ask).
2. Each lifecycle stage is a self-contained instruction file. Execute the one
   matching the task:

| Command | Purpose | Instructions |
|---|---|---|
{table}

3. Instruction files reference framework paths as `${{CLAUDE_PLUGIN_ROOT}}` —
   that is this repository's root. Claude Code resolves it natively; other
   harnesses substitute the repo path (the Copilot adapter under
   `.github/prompts/` and the native-skill copies under `.github/skills/`
   are pre-substituted; regenerate with `python3 scripts/build_copilot.py`).
4. Task state lives in `work/<task-id>/` workspaces (`STATUS.md` = resume
   point, `scope-contract.md` = scope truth, `ASSUMPTIONS.md` = logged
   judgment calls, `evidence/` = verification outputs).
5. Review procedures in `agents/` (scope-auditor, code-reviewer,
   doc-fact-checker) run as subagents where supported — Claude Code agents
   natively, Copilot custom agents via the generated `.github/agents/` — and
   as separate fresh passes held to their report formats everywhere else.
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--target", type=Path, default=None,
                    help="work repo to install the Copilot adapter into (default: the stack repo)")
    ap.add_argument("--stack-root", type=Path, default=Path(__file__).resolve().parent.parent,
                    help="location of the software-engineer-stack repo")
    args = ap.parse_args()

    stack = args.stack_root.resolve()
    target = (args.target or stack).resolve()
    if not (stack / "skills").is_dir():
        sys.exit(f"error: {stack} does not look like the stack repo (no skills/)")
    # inside the stack repo, references are repo-relative; elsewhere, absolute
    root_ref = "." if target == stack else str(stack)

    skill_dirs = sorted(d for d in (stack / "skills").iterdir() if (d / "SKILL.md").is_file())
    names = []
    for d in skill_dirs:
        fm, body = parse_frontmatter((d / "SKILL.md").read_text(), d / "SKILL.md")
        names.append(fm["name"])
        write_generated(target / ".github" / "prompts" / f"{fm['name']}.prompt.md",
                        build_prompt(fm, body, root_ref))
        write_generated(target / ".github" / "skills" / fm["name"] / "SKILL.md",
                        build_skill(fm, body, root_ref))

    agent_files = sorted((stack / "agents").glob("*.md"))
    for f in agent_files:
        fm, body = parse_frontmatter(f.read_text(), f)
        write_generated(target / ".github" / "agents" / f"{fm['name']}.agent.md",
                        build_agent(fm, body, root_ref))

    write_generated(target / ".github" / "copilot-instructions.md",
                    build_instructions(root_ref, names))
    write_generated(stack / "AGENTS.md", build_agents_md(skill_dirs))
    print(f"done: {len(names)} prompts + {len(names)} native skills + "
          f"{len(agent_files)} custom agents → {target / '.github'}")


if __name__ == "__main__":
    main()
